# Generated by Django 3.1.2 on 2021-10-21 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(editable=False, default=0)),
                ('week', models.IntegerField()),
                ('day', models.CharField(choices=[('1', 'Sun'), ('2', 'Mon'), ('3', 'Tue'), ('4', 'Wen'), ('5', 'Thur'), ('6', 'Fri'), ('7', 'Sat')], default='1', max_length=20)),
                ('rainData', models.IntegerField(default=0)),
            ],
        ),
    ]
