# Generated by Django 3.1.2 on 2021-10-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_chart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Date',
            field=models.DateField(editable=False),
        ),
    ]
