# Generated by Django 3.1.2 on 2021-10-21 22:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_series_chart', '0002_auto_20211022_0116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='Date',
        ),
        migrations.AddField(
            model_name='data',
            name='timestamp',
            field=models.DateField(default=datetime.date.today, editable=False),
        ),
    ]
